### PR TITLE
no open gl

### PR DESCRIPTION
**Pull request by CJ-Wright**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge-admin please rerender

**Comment by tschoonj** [comment]
Could you please comment on what problems you are talking about in:

https://github.com/conda-forge/silx-feedstock/blob/df79f4952d37ab0916824fc55257493e7a16cb15/recipe/meta.yaml#L37-L38

Also: I didn't realize there was a PR open for 0.9.0 in #14: could you perhaps cherry pick the version bump commit into this PR as well?

**Comment by CJ-Wright** [comment]
Ideally we'd do the version bump and this separately so that we can keep the issues of one from bleeding into the other.

**Comment by CJ-Wright** [comment]
We're having issues with some of the downstream packages https://github.com/conda-forge/xpdsim-feedstock/pull/6

**Comment by CJ-Wright** [comment]
I'd be open to putting out a subpackage with pyopengl installed, but I'd like to get this in today.

**Comment by CJ-Wright** [comment]
@conda-forge-admin please rerender

**Pull request merged**
